server:
  ssl:
    key-store: /usr/local/exam/ssl/tomcat.jks
    key-password: Qwer!@#$%

spring:
  redis:
    host: localhost
  datasource:
    url: jdbc:mysql://localhost:3306/exam
    username: root
    password: 123456

system:
  fdfs-ngix: http://localhost:8888

fdfs:
  tracker-list:
    - localhost:22122
